### ISSUE TITLE
EDD regions for "Prince William Sound Economic Development District" looks odd

### ISSUE THREAD

**Issue by soichih** [iuctil/apred#92]
When I select "Prince William Sound Economic Development District", it shows the same county several times. I suspect the EDD table has corrupt fips?

![image](https://user-images.githubusercontent.com/923896/107979284-50678c00-6f8c-11eb-8d3a-01a0d9aad95a.png)

**Comment by iobik** [comment]
@soichih @ljpaul What is the status of this issue?

**Comment by ljpaul** [comment]
I am not super familiar with the data source for the EDD districts. Alaska is tricky because of, in part, the different vernacular for geographies. There are five entities in the district according to the district webpage... but those five are all not necessarily "counties."

https://en.wikipedia.org/wiki/Valdez%E2%80%93Cordova_Census_Area,_Alaska

So, I assume that the five elements within that census area are:

- Chenega (Census-designated place)
- Cordova (City)
- Tatilek (Census-designated place)
- Valdez (City)
- Whittier (City)

Not to pass the potato, but we should ask Brittany about this. (I cannot find the data source table in our code to investigate.)

**Comment by iobik** [comment]
@blj4 What do you think about this issue?

**Comment by blj4** [comment]
Yep, Logan hit the nail on the head.

Alaska is very strange with its geographies and the list sent from EDA has the same county listed four times:

***@***.***D73506.24A75160]

As Logan said, these are not actually COUNTIES, so the closest thing we have for each of them is FIPS code 261 and 926.

I’m not sure what database table is being used on your end for this tool, but you could theoretically remove the duplicate records. I will not do that in stats4 since this is the list as provided by EDA.

From: iobik ***@***.***>
Sent: Friday, April 16, 2021 8:24 PM
To: soichih/apred ***@***.***>
Cc: Hotchkiss, Brittany Lynn ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [soichih/apred] EDD regions for "Prince William Sound Economic Development District" looks odd (#92)

This message was sent from a non-IU address. Please exercise caution when clicking links or opening attachments from external sources.


@blj4<https://github.com/blj4> What do you think about this issue?

**Comment by soichih** [comment]
Maybe we should remove the records that belong to Alaska?

**Comment by blj4** [comment]
I wouldn’t remove Alaska from the tool. All of the counties in the Prince William Sound Economic Development District are in Alaska, so that would remove that EDD altogether.

What table are you using to get the EDD definitions? We could remove the duplicate records for that EDD.

From: Soichi Hayashi ***@***.***>
Sent: Monday, April 19, 2021 10:45 AM
To: soichih/apred ***@***.***>
Cc: Hotchkiss, Brittany Lynn ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [soichih/apred] EDD regions for "Prince William Sound Economic Development District" looks odd (#92)

This message was sent from a non-IU address. Please exercise caution when clicking links or opening attachments from external sources.

Maybe we should remove the records that belong to Alaska?

**Comment by soichih** [comment]
[config.stats_america.db_stats4]
```
SELECT * from regions_eda
```

**Comment by ljpaul** [comment]
Brittany removed some erroneous records. Fixed.

**Comment by wliao1** [comment]
![image](https://user-images.githubusercontent.com/24637486/120546645-1f398d00-c3be-11eb-9526-8d6214d9b5ce.png)

Issue does not appear to be resolved on website; can we reopen this issue?

**Comment by blj4** [comment]
I’m not sure if there needs to be a refresh of that table? There should only be one county showing.

From: wliao1 ***@***.***>
Sent: Wednesday, June 2, 2021 4:19 PM
To: iuctil/apred ***@***.***>
Cc: Hotchkiss, Brittany Lynn ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [iuctil/apred] EDD regions for "Prince William Sound Economic Development District" looks odd (#92)

This message was sent from a non-IU address. Please exercise caution when clicking links or opening attachments from external sources.


[image]<https://user-images.githubusercontent.com/24637486/120546645-1f398d00-c3be-11eb-9526-8d6214d9b5ce.png>

Issue does not appear to be resolved on website; can we reopen this issue?

**Comment by soichih** [comment]
I just noticed that "Prince William Sound Economic Development District" is still broken(?) 

![image](https://user-images.githubusercontent.com/923896/120871791-b2afc100-c56a-11eb-8518-c7b21b19feb3.png)

So let me re-open this.

**Comment by soichih** [comment]
Sorry, I've reload regions list table and now it's showing correct list.

![image](https://user-images.githubusercontent.com/923896/121064046-1584a080-c795-11eb-8471-0cbe0f2f9cac.png)

I guess I forgot to reload the table for production.
